spring:
  application:
    name: productapi
  datasource:
    url: jdbc:h2:file:./data/productDB
    driver-class-name: org.h2.Driver
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  file:
    name: logs/product-api.log
  level:
    root: INFO
    com.supun.productapi: INFO
