name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_KEY }}'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/my-app:$GITHUB_SHA .

      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/my-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: my-app
          image: gcr.io/${{ secrets.GCP_PROJECT }}/my-app:$GITHUB_SHA
          region: ${{ secrets.GCP_REGION }}
          allow-unauthenticated: true
